### ISSUE TITLE
com.mparticle:android-onetrust-kit contains org.json jar file

### ISSUE THREAD

**Issue by rossbacher** [mparticle-integrations/mparticle-android-integration-onetrust#10]
This PR https://github.com/mparticle-integrations/mparticle-android-integration-onetrust/pull/5 and especially this line:
```
implementation fileTree(dir: 'libs', include: ['*.jar'])
```

leads to the inclusion of the `java-json.jar` file into the `.aar`:

![Screen Shot 2022-01-06 at 13 30 16](https://user-images.githubusercontent.com/6025027/148454862-1edef3e6-2e7a-4536-8cef-e8b08ee05fbd.png)

However, as org.json is already part of the Android system image this create a conflict as now the same classes are twice on the classpath.

Imho this should be listed here as `compileOnly` to avoid this integration into the `.aar`.

**Comment by willpassidomo** [comment]
Hey @rossbacher thanks for catching this, definitely an oversight on our part. We only need this package for our unit tests, so we've replaced it with `testImplementation` [PR](https://github.com/mparticle-integrations/mparticle-android-integration-onetrust/pull/11) just got merged, should be released by Wednesday :)
